-- =====================================================
-- SISTEMA ACADÉMICO - ORACLE DATABASE 19c
-- Script: 06_roles_privilegios.sql
-- Propósito: Creación de roles y asignación de privilegios
-- Autor: Sistema Académico
-- Fecha: 28/10/2025
-- =====================================================

-- =====================================================
-- CREACIÓN DE ROLES DEL SISTEMA
-- =====================================================

-- ROL 1: ADMINISTRADOR DEL SISTEMA
-- Justificación: Control total para administradores de BD
CREATE ROLE ROL_ADMINISTRADOR;

-- ROL 2: COORDINADOR ACADÉMICO
-- Justificación: Gestión de planificación académica
CREATE ROLE ROL_COORDINADOR_ACADEMICO;

-- ROL 3: DOCENTE
-- Justificación: Gestión de calificaciones y consultas académicas
CREATE ROLE ROL_DOCENTE;

-- ROL 4: ESTUDIANTE
-- Justificación: Consulta de información personal y académica
CREATE ROLE ROL_ESTUDIANTE;

-- ROL 5: REGISTRO ACADÉMICO
-- Justificación: Gestión de matrículas y seguimiento académico
CREATE ROLE ROL_REGISTRO_ACADEMICO;

-- ROL 6: ANALISTA
-- Justificación: Generación de reportes y análisis estadísticos
CREATE ROLE ROL_ANALISTA;

PROMPT '========================================='
PROMPT 'Roles creados exitosamente'
PROMPT '========================================='

-- =====================================================
-- PRIVILEGIOS PARA ROL_ADMINISTRADOR
-- Justificación: Acceso completo a todas las tablas y objetos
-- del sistema para tareas administrativas y mantenimiento
-- =====================================================

-- Acceso total a tablas maestras
GRANT ALL ON FACULTAD TO ROL_ADMINISTRADOR;
GRANT ALL ON PROGRAMA_ACADEMICO TO ROL_ADMINISTRADOR;
GRANT ALL ON ESTUDIANTE TO ROL_ADMINISTRADOR;
GRANT ALL ON DOCENTE TO ROL_ADMINISTRADOR;

-- Acceso total a tablas de catálogos
GRANT ALL ON ASIGNATURA TO ROL_ADMINISTRADOR;
GRANT ALL ON PRERREQUISITO TO ROL_ADMINISTRADOR;
GRANT ALL ON PERIODO_ACADEMICO TO ROL_ADMINISTRADOR;
GRANT ALL ON TIPO_ACTIVIDAD_EVALUATIVA TO ROL_ADMINISTRADOR;
GRANT ALL ON REGLA_EVALUACION TO ROL_ADMINISTRADOR;

-- Acceso total a tablas transaccionales
GRANT ALL ON GRUPO TO ROL_ADMINISTRADOR;
GRANT ALL ON HORARIO TO ROL_ADMINISTRADOR;
GRANT ALL ON MATRICULA TO ROL_ADMINISTRADOR;
GRANT ALL ON DETALLE_MATRICULA TO ROL_ADMINISTRADOR;
GRANT ALL ON CALIFICACION TO ROL_ADMINISTRADOR;
GRANT ALL ON NOTA_DEFINITIVA TO ROL_ADMINISTRADOR;

-- Acceso total a tablas de auditoría y seguridad
GRANT ALL ON HISTORIAL_RIESGO TO ROL_ADMINISTRADOR;
GRANT ALL ON AUDITORIA TO ROL_ADMINISTRADOR;
GRANT ALL ON USUARIO_SISTEMA TO ROL_ADMINISTRADOR;
GRANT ALL ON LOG_ACCESO TO ROL_ADMINISTRADOR;

-- Acceso total a tablas especiales
GRANT ALL ON DIRECTOR_TRABAJO_GRADO TO ROL_ADMINISTRADOR;

-- Acceso a todas las vistas
GRANT SELECT ON VW_ESTUDIANTES_PUBLICO TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_DOCENTES_PUBLICO TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_CALIFICACIONES_ANONIMAS TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_AUDITORIA_RESUMIDA TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_ESTUDIANTES_POR_PROGRAMA TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_MATRICULAS_POR_PERIODO TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_RENDIMIENTO_POR_ASIGNATURA TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_CARGA_DOCENTE TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_ESTUDIANTES_RIESGO TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_GRUPOS_DISPONIBLES TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_HISTORIAL_ACADEMICO TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_CALENDARIO_VIGENTE TO ROL_ADMINISTRADOR;
GRANT SELECT ON VW_CONFLICTOS_HORARIO TO ROL_ADMINISTRADOR;

-- Acceso a secuencias
GRANT SELECT, ALTER ON SEQ_FACULTAD TO ROL_ADMINISTRADOR;
GRANT SELECT, ALTER ON SEQ_PROGRAMA_ACADEMICO TO ROL_ADMINISTRADOR;
GRANT SELECT, ALTER ON SEQ_MATRICULA TO ROL_ADMINISTRADOR;
GRANT SELECT, ALTER ON SEQ_CALIFICACION TO ROL_ADMINISTRADOR;
GRANT SELECT, ALTER ON SEQ_AUDITORIA TO ROL_ADMINISTRADOR;

PROMPT 'Privilegios asignados a ROL_ADMINISTRADOR'

-- =====================================================
-- PRIVILEGIOS PARA ROL_COORDINADOR_ACADEMICO
-- Justificación: Gestión de grupos, horarios, asignaturas
-- y reglas de evaluación para planificación académica
-- =====================================================

-- Consulta de información base
GRANT SELECT ON FACULTAD TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON PROGRAMA_ACADEMICO TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON ESTUDIANTE TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON DOCENTE TO ROL_COORDINADOR_ACADEMICO;

-- Gestión de asignaturas y prerrequisitos
GRANT SELECT, INSERT, UPDATE ON ASIGNATURA TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRERREQUISITO TO ROL_COORDINADOR_ACADEMICO;

-- Gestión de periodos académicos
GRANT SELECT, INSERT, UPDATE ON PERIODO_ACADEMICO TO ROL_COORDINADOR_ACADEMICO;

-- Gestión completa de grupos y horarios
GRANT SELECT, INSERT, UPDATE, DELETE ON GRUPO TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON HORARIO TO ROL_COORDINADOR_ACADEMICO;

-- Gestión de reglas de evaluación
GRANT SELECT, INSERT, UPDATE, DELETE ON REGLA_EVALUACION TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON TIPO_ACTIVIDAD_EVALUATIVA TO ROL_COORDINADOR_ACADEMICO;

-- Consulta de información académica
GRANT SELECT ON MATRICULA TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON DETALLE_MATRICULA TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON CALIFICACION TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON NOTA_DEFINITIVA TO ROL_COORDINADOR_ACADEMICO;

-- Acceso a vistas relevantes
GRANT SELECT ON VW_ESTUDIANTES_PUBLICO TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_DOCENTES_PUBLICO TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_ESTUDIANTES_POR_PROGRAMA TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_MATRICULAS_POR_PERIODO TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_RENDIMIENTO_POR_ASIGNATURA TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_CARGA_DOCENTE TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_GRUPOS_DISPONIBLES TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_CALENDARIO_VIGENTE TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON VW_CONFLICTOS_HORARIO TO ROL_COORDINADOR_ACADEMICO;

-- Acceso a secuencias necesarias
GRANT SELECT ON SEQ_GRUPO TO ROL_COORDINADOR_ACADEMICO;
GRANT SELECT ON SEQ_HORARIO TO ROL_COORDINADOR_ACADEMICO;

PROMPT 'Privilegios asignados a ROL_COORDINADOR_ACADEMICO'

-- =====================================================
-- PRIVILEGIOS PARA ROL_DOCENTE
-- Justificación: Consulta de grupos asignados y gestión
-- de calificaciones de sus estudiantes
-- =====================================================

-- Consulta de información personal
GRANT SELECT ON DOCENTE TO ROL_DOCENTE;

-- Consulta de grupos asignados
GRANT SELECT ON GRUPO TO ROL_DOCENTE;
GRANT SELECT ON HORARIO TO ROL_DOCENTE;
GRANT SELECT ON ASIGNATURA TO ROL_DOCENTE;
GRANT SELECT ON PERIODO_ACADEMICO TO ROL_DOCENTE;

-- Consulta de estudiantes matriculados
GRANT SELECT ON ESTUDIANTE TO ROL_DOCENTE;
GRANT SELECT ON MATRICULA TO ROL_DOCENTE;
GRANT SELECT ON DETALLE_MATRICULA TO ROL_DOCENTE;

-- Gestión de calificaciones (crear, modificar, consultar)
GRANT SELECT, INSERT, UPDATE ON CALIFICACION TO ROL_DOCENTE;
GRANT SELECT, INSERT, UPDATE ON NOTA_DEFINITIVA TO ROL_DOCENTE;

-- Consulta de reglas de evaluación
GRANT SELECT ON REGLA_EVALUACION TO ROL_DOCENTE;
GRANT SELECT ON TIPO_ACTIVIDAD_EVALUATIVA TO ROL_DOCENTE;

-- Acceso a vistas específicas
GRANT SELECT ON VW_DOCENTES_PUBLICO TO ROL_DOCENTE;
GRANT SELECT ON VW_ESTUDIANTES_PUBLICO TO ROL_DOCENTE;
GRANT SELECT ON VW_RENDIMIENTO_POR_ASIGNATURA TO ROL_DOCENTE;
GRANT SELECT ON VW_CARGA_DOCENTE TO ROL_DOCENTE;
GRANT SELECT ON VW_GRUPOS_DISPONIBLES TO ROL_DOCENTE;
GRANT SELECT ON VW_HISTORIAL_ACADEMICO TO ROL_DOCENTE;
GRANT SELECT ON VW_CALENDARIO_VIGENTE TO ROL_DOCENTE;

-- Acceso a secuencias de calificaciones
GRANT SELECT ON SEQ_CALIFICACION TO ROL_DOCENTE;
GRANT SELECT ON SEQ_NOTA_DEFINITIVA TO ROL_DOCENTE;

-- Gestión de trabajos de grado (solo consulta y actualización)
GRANT SELECT, UPDATE ON DIRECTOR_TRABAJO_GRADO TO ROL_DOCENTE;

PROMPT 'Privilegios asignados a ROL_DOCENTE'

-- =====================================================
-- PRIVILEGIOS PARA ROL_ESTUDIANTE
-- Justificación: Solo consulta de información propia
-- y datos públicos del sistema académico
-- =====================================================

-- Consulta de información personal (limitada por aplicación)
GRANT SELECT ON ESTUDIANTE TO ROL_ESTUDIANTE;

-- Consulta de información académica propia
GRANT SELECT ON MATRICULA TO ROL_ESTUDIANTE;
GRANT SELECT ON DETALLE_MATRICULA TO ROL_ESTUDIANTE;
GRANT SELECT ON CALIFICACION TO ROL_ESTUDIANTE;
GRANT SELECT ON NOTA_DEFINITIVA TO ROL_ESTUDIANTE;

-- Consulta de información institucional
GRANT SELECT ON FACULTAD TO ROL_ESTUDIANTE;
GRANT SELECT ON PROGRAMA_ACADEMICO TO ROL_ESTUDIANTE;
GRANT SELECT ON ASIGNATURA TO ROL_ESTUDIANTE;
GRANT SELECT ON PERIODO_ACADEMICO TO ROL_ESTUDIANTE;
GRANT SELECT ON GRUPO TO ROL_ESTUDIANTE;
GRANT SELECT ON HORARIO TO ROL_ESTUDIANTE;

-- Consulta de prerrequisitos
GRANT SELECT ON PRERREQUISITO TO ROL_ESTUDIANTE;

-- Acceso solo a vistas públicas
GRANT SELECT ON VW_ESTUDIANTES_PUBLICO TO ROL_ESTUDIANTE;
GRANT SELECT ON VW_DOCENTES_PUBLICO TO ROL_ESTUDIANTE;
GRANT SELECT ON VW_GRUPOS_DISPONIBLES TO ROL_ESTUDIANTE;
GRANT SELECT ON VW_HISTORIAL_ACADEMICO TO ROL_ESTUDIANTE;
GRANT SELECT ON VW_CALENDARIO_VIGENTE TO ROL_ESTUDIANTE;

-- Consulta de trabajos de grado propios
GRANT SELECT ON DIRECTOR_TRABAJO_GRADO TO ROL_ESTUDIANTE;

PROMPT 'Privilegios asignados a ROL_ESTUDIANTE'

-- =====================================================
-- PRIVILEGIOS PARA ROL_REGISTRO_ACADEMICO
-- Justificación: Gestión completa de matrículas,
-- seguimiento académico y actualización de información
-- =====================================================

-- Consulta y actualización de estudiantes
GRANT SELECT, INSERT, UPDATE ON ESTUDIANTE TO ROL_REGISTRO_ACADEMICO;

-- Consulta de estructura académica
GRANT SELECT ON FACULTAD TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON PROGRAMA_ACADEMICO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON ASIGNATURA TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON PERIODO_ACADEMICO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON GRUPO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON HORARIO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON PRERREQUISITO TO ROL_REGISTRO_ACADEMICO;

-- Gestión completa de matrículas
GRANT SELECT, INSERT, UPDATE, DELETE ON MATRICULA TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT, INSERT, UPDATE, DELETE ON DETALLE_MATRICULA TO ROL_REGISTRO_ACADEMICO;

-- Consulta de calificaciones
GRANT SELECT ON CALIFICACION TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON NOTA_DEFINITIVA TO ROL_REGISTRO_ACADEMICO;

-- Gestión de historial de riesgo
GRANT SELECT, INSERT, UPDATE ON HISTORIAL_RIESGO TO ROL_REGISTRO_ACADEMICO;

-- Gestión de trabajos de grado
GRANT SELECT, INSERT, UPDATE ON DIRECTOR_TRABAJO_GRADO TO ROL_REGISTRO_ACADEMICO;

-- Acceso a vistas de gestión
GRANT SELECT ON VW_ESTUDIANTES_PUBLICO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON VW_ESTUDIANTES_POR_PROGRAMA TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON VW_MATRICULAS_POR_PERIODO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON VW_RENDIMIENTO_POR_ASIGNATURA TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON VW_ESTUDIANTES_RIESGO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON VW_GRUPOS_DISPONIBLES TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON VW_HISTORIAL_ACADEMICO TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON VW_CALENDARIO_VIGENTE TO ROL_REGISTRO_ACADEMICO;

-- Acceso a secuencias de matrícula
GRANT SELECT ON SEQ_MATRICULA TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON SEQ_DETALLE_MATRICULA TO ROL_REGISTRO_ACADEMICO;
GRANT SELECT ON SEQ_HISTORIAL_RIESGO TO ROL_REGISTRO_ACADEMICO;

PROMPT 'Privilegios asignados a ROL_REGISTRO_ACADEMICO'

-- =====================================================
-- PRIVILEGIOS PARA ROL_ANALISTA
-- Justificación: Acceso de solo lectura a vistas
-- y tablas para generación de reportes estadísticos
-- sin datos sensibles
-- =====================================================

-- Consulta de vistas analíticas (sin datos personales sensibles)
GRANT SELECT ON VW_CALIFICACIONES_ANONIMAS TO ROL_ANALISTA;
GRANT SELECT ON VW_ESTUDIANTES_POR_PROGRAMA TO ROL_ANALISTA;
GRANT SELECT ON VW_MATRICULAS_POR_PERIODO TO ROL_ANALISTA;
GRANT SELECT ON VW_RENDIMIENTO_POR_ASIGNATURA TO ROL_ANALISTA;
GRANT SELECT ON VW_CARGA_DOCENTE TO ROL_ANALISTA;
GRANT SELECT ON VW_GRUPOS_DISPONIBLES TO ROL_ANALISTA;
GRANT SELECT ON VW_CALENDARIO_VIGENTE TO ROL_ANALISTA;
GRANT SELECT ON VW_CONFLICTOS_HORARIO TO ROL_ANALISTA;

-- Consulta limitada de tablas base para análisis
GRANT SELECT ON PROGRAMA_ACADEMICO TO ROL_ANALISTA;
GRANT SELECT ON FACULTAD TO ROL_ANALISTA;
GRANT SELECT ON ASIGNATURA TO ROL_ANALISTA;
GRANT SELECT ON PERIODO_ACADEMICO TO ROL_ANALISTA;
GRANT SELECT ON GRUPO TO ROL_ANALISTA;
GRANT SELECT ON MATRICULA TO ROL_ANALISTA;
GRANT SELECT ON DETALLE_MATRICULA TO ROL_ANALISTA;

-- Solo estadísticas de calificaciones (sin identificación)
GRANT SELECT ON NOTA_DEFINITIVA TO ROL_ANALISTA;

-- Consulta de auditoría resumida
GRANT SELECT ON VW_AUDITORIA_RESUMIDA TO ROL_ANALISTA;

PROMPT 'Privilegios asignados a ROL_ANALISTA'

-- =====================================================
-- PRIVILEGIOS ADICIONALES PARA EJECUCIÓN DE PAQUETES
-- Nota: Se asignarán después de crear los paquetes
-- =====================================================

-- Los siguientes grants se ejecutarán en el script de paquetes:
-- GRANT EXECUTE ON PKG_MATRICULA TO ROL_REGISTRO_ACADEMICO;
-- GRANT EXECUTE ON PKG_CALIFICACION TO ROL_DOCENTE;
-- GRANT EXECUTE ON PKG_AUDITORIA TO ROL_ADMINISTRADOR;

-- =====================================================
-- CREACIÓN DE USUARIOS DE EJEMPLO (OPCIONAL)
-- Nota: Descomentar y ajustar según necesidades
-- =====================================================


-- Usuario administrador del sistema
CREATE USER usr_admin IDENTIFIED BY Admin2025#
DEFAULT TABLESPACE TBS_MAESTROS
TEMPORARY TABLESPACE TBS_TEMP_ACADEMICO
QUOTA UNLIMITED ON TBS_MAESTROS;

GRANT CONNECT, RESOURCE TO usr_admin;
GRANT ROL_ADMINISTRADOR TO usr_admin;

-- Usuario coordinador académico
CREATE USER usr_coordinador IDENTIFIED BY Coord2025#
DEFAULT TABLESPACE TBS_MAESTROS
TEMPORARY TABLESPACE TBS_TEMP_ACADEMICO
QUOTA 100M ON TBS_MAESTROS;

GRANT CONNECT TO usr_coordinador;
GRANT ROL_COORDINADOR_ACADEMICO TO usr_coordinador;

-- Usuario docente de ejemplo
CREATE USER usr_docente IDENTIFIED BY Docente2025#
DEFAULT TABLESPACE TBS_MAESTROS
TEMPORARY TABLESPACE TBS_TEMP_ACADEMICO
QUOTA 50M ON TBS_MAESTROS;

GRANT CONNECT TO usr_docente;
GRANT ROL_DOCENTE TO usr_docente;

-- Usuario registro académico
CREATE USER usr_registro IDENTIFIED BY Registro2025#
DEFAULT TABLESPACE TBS_MAESTROS
TEMPORARY TABLESPACE TBS_TEMP_ACADEMICO
QUOTA 200M ON TBS_MAESTROS;

GRANT CONNECT TO usr_registro;
GRANT ROL_REGISTRO_ACADEMICO TO usr_registro;

-- Usuario analista
CREATE USER usr_analista IDENTIFIED BY Analista2025#
DEFAULT TABLESPACE TBS_MAESTROS
TEMPORARY TABLESPACE TBS_TEMP_ACADEMICO
QUOTA 50M ON TBS_MAESTROS;

GRANT CONNECT TO usr_analista;
GRANT ROL_ANALISTA TO usr_analista;

PROMPT 'Usuarios de ejemplo creados'


-- =====================================================
-- RESUMEN DE ROLES Y PRIVILEGIOS
-- =====================================================

PROMPT '========================================='
PROMPT 'RESUMEN DE ROLES Y PRIVILEGIOS'
PROMPT '========================================='
PROMPT ''
PROMPT 'ROL_ADMINISTRADOR:'
PROMPT '  - Acceso total a todas las tablas'
PROMPT '  - Gestión completa del sistema'
PROMPT '  - Acceso a todas las vistas'
PROMPT ''
PROMPT 'ROL_COORDINADOR_ACADEMICO:'
PROMPT '  - Gestión de grupos y horarios'
PROMPT '  - Configuración de asignaturas'
PROMPT '  - Planificación académica'
PROMPT ''
PROMPT 'ROL_DOCENTE:'
PROMPT '  - Consulta de grupos asignados'
PROMPT '  - Gestión de calificaciones'
PROMPT '  - Consulta de estudiantes'
PROMPT ''
PROMPT 'ROL_ESTUDIANTE:'
PROMPT '  - Consulta de información personal'
PROMPT '  - Consulta de calificaciones'
PROMPT '  - Consulta de grupos disponibles'
PROMPT ''
PROMPT 'ROL_REGISTRO_ACADEMICO:'
PROMPT '  - Gestión de matrículas'
PROMPT '  - Seguimiento académico'
PROMPT '  - Gestión de estudiantes'
PROMPT ''
PROMPT 'ROL_ANALISTA:'
PROMPT '  - Consulta de vistas analíticas'
PROMPT '  - Generación de reportes'
PROMPT '  - Análisis estadísticos'
PROMPT ''
PROMPT '========================================='
PROMPT 'Roles y privilegios configurados exitosamente'
PROMPT '========================================='

-- Consultar roles creados (requiere privilegios DBA)
-- Si no tiene privilegios, verifique con: SELECT * FROM user_sys_privs WHERE privilege LIKE '%ROLE%';
-- SELECT role FROM dba_roles WHERE role LIKE 'ROL_%' ORDER BY role;

-- Consultar privilegios por rol (requiere privilegios de DBA)
-- SELECT * FROM dba_tab_privs WHERE grantee LIKE 'ROL_%' ORDER BY grantee, table_name;
