-- =====================================================
-- SCRIPT: OTORGAR PERMISOS ORDS A USUARIO ACADEMICO
-- Descripción: Otorga los privilegios necesarios para 
--              que ACADEMICO pueda crear módulos ORDS
-- Ejecutar como: SYS (con rol SYSDBA)
-- =====================================================

SET SERVEROUTPUT ON
SET ECHO ON

PROMPT '========================================='
PROMPT 'OTORGANDO PERMISOS ORDS A ACADEMICO'
PROMPT '========================================='


-- Permisos ORDS y ejecución de endpoints para ACADEMICO
GRANT INHERIT PRIVILEGES ON USER ORDS_METADATA TO ACADEMICO;
GRANT INHERIT PRIVILEGES ON USER ORDS_PUBLIC_USER TO ACADEMICO;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ACADEMICO;
GRANT EXECUTE ON SYS.UTL_I18N TO ACADEMICO;

-- Acceso total a tablas maestras y transaccionales
GRANT ALL ON FACULTAD TO ACADEMICO;
GRANT ALL ON PROGRAMA_ACADEMICO TO ACADEMICO;
GRANT ALL ON ESTUDIANTE TO ACADEMICO;
GRANT ALL ON DOCENTE TO ACADEMICO;
GRANT ALL ON ASIGNATURA TO ACADEMICO;
GRANT ALL ON PRERREQUISITO TO ACADEMICO;
GRANT ALL ON PERIODO_ACADEMICO TO ACADEMICO;
GRANT ALL ON TIPO_ACTIVIDAD_EVALUATIVA TO ACADEMICO;
GRANT ALL ON REGLA_EVALUACION TO ACADEMICO;
GRANT ALL ON GRUPO TO ACADEMICO;
GRANT ALL ON HORARIO TO ACADEMICO;
GRANT ALL ON MATRICULA TO ACADEMICO;
GRANT ALL ON DETALLE_MATRICULA TO ACADEMICO;
GRANT ALL ON CALIFICACION TO ACADEMICO;
GRANT ALL ON NOTA_DEFINITIVA TO ACADEMICO;
GRANT ALL ON HISTORIAL_RIESGO TO ACADEMICO;
GRANT ALL ON AUDITORIA TO ACADEMICO;
GRANT ALL ON USUARIO_SISTEMA TO ACADEMICO;
GRANT ALL ON LOG_ACCESO TO ACADEMICO;
GRANT ALL ON DIRECTOR_TRABAJO_GRADO TO ACADEMICO;

-- Acceso a vistas
GRANT SELECT ON VW_ESTUDIANTES_PUBLICO TO ACADEMICO;
GRANT SELECT ON VW_DOCENTES_PUBLICO TO ACADEMICO;
GRANT SELECT ON VW_CALIFICACIONES_ANONIMAS TO ACADEMICO;
GRANT SELECT ON VW_AUDITORIA_RESUMIDA TO ACADEMICO;
GRANT SELECT ON VW_ESTUDIANTES_POR_PROGRAMA TO ACADEMICO;
GRANT SELECT ON VW_MATRICULAS_POR_PERIODO TO ACADEMICO;
GRANT SELECT ON VW_RENDIMIENTO_POR_ASIGNATURA TO ACADEMICO;
GRANT SELECT ON VW_CARGA_DOCENTE TO ACADEMICO;
GRANT SELECT ON VW_ESTUDIANTES_RIESGO TO ACADEMICO;
GRANT SELECT ON VW_GRUPOS_DISPONIBLES TO ACADEMICO;
GRANT SELECT ON VW_HISTORIAL_ACADEMICO TO ACADEMICO;
GRANT SELECT ON VW_CALENDARIO_VIGENTE TO ACADEMICO;
GRANT SELECT ON VW_CONFLICTOS_HORARIO TO ACADEMICO;

-- Acceso a secuencias
GRANT SELECT, ALTER ON SEQ_FACULTAD TO ACADEMICO;
GRANT SELECT, ALTER ON SEQ_PROGRAMA_ACADEMICO TO ACADEMICO;
GRANT SELECT, ALTER ON SEQ_MATRICULA TO ACADEMICO;
GRANT SELECT, ALTER ON SEQ_CALIFICACION TO ACADEMICO;
GRANT SELECT, ALTER ON SEQ_AUDITORIA TO ACADEMICO;
GRANT SELECT ON SEQ_GRUPO TO ACADEMICO;
GRANT SELECT ON SEQ_HORARIO TO ACADEMICO;
GRANT SELECT ON SEQ_DETALLE_MATRICULA TO ACADEMICO;
GRANT SELECT ON SEQ_HISTORIAL_RIESGO TO ACADEMICO;
GRANT SELECT ON SEQ_NOTA_DEFINITIVA TO ACADEMICO;

SELECT grantee, privilege, grantable
FROM dba_tab_privs
WHERE grantee = 'ACADEMICO'
  AND grantor = 'ORDS_METADATA';

PROMPT ''
PROMPT '✓ Privilegios ORDS otorgados exitosamente a ACADEMICO'
PROMPT ''

EXIT;
